-- Wholesale net revenue of each product line generated by warehouse per month (question 1)
WITH productyear AS (
	SELECT
		order_number,
		CASE
			WHEN EXTRACT(MONTH FROM date) = 6 THEN 'June'
			WHEN EXTRACT(MONTH FROM date) = 7 THEN 'July'
			ELSE 'August' END AS month
	FROM sales
	WHERE client_type = 'Wholesale'
)

SELECT
	s.product_line,
	month,
	s.warehouse,
	(SUM(s.total) - SUM(s.payment_fee)) AS net_revenue
FROM sales s
INNER JOIN productyear p
ON s.order_number = p.order_number
GROUP BY s.product_line, month, warehouse
ORDER BY warehouse, s.product_line, month, net_revenue DESC;

-- Generated net revenue for each warehouse (question 2)

SELECT 
	warehouse, 
	(SUM(total)-SUM(payment_fee)) AS net_revenue 
FROM sales 
GROUP BY warehouse 
ORDER BY net_revenue DESC;

-- Top performing product lines in each warehouses (question 3)
WITH product_warehouse AS (
	SELECT
		product_line,
		warehouse,
		SUM(total) - SUM(payment_fee) AS net_revenue
	FROM sales
	GROUP BY product_line, warehouse
),

product_rank AS (
	SELECT
		product_line,
		warehouse,
		net_revenue,
		RANK() OVER(PARTITION BY warehouse ORDER BY net_revenue DESC) AS rank_product
	FROM product_warehouse
)

SELECT
	product_line,
	warehouse,
	net_revenue,
	rank_product
FROM product_rank
WHERE rank_product <= 3;


-- Worst product line performance in each warehouse (question 4)
WITH product_warehouse AS (
	SELECT
		product_line,
		warehouse,
		SUM(total) - SUM(payment_fee) AS net_revenue,
		RANK() OVER(PARTITION BY warehouse ORDER BY SUM(total) - SUM(payment_fee)) AS rank_product
	FROM sales
	GROUP BY product_line, warehouse
)

SELECT
	product_line,
	warehouse,
	net_revenue
FROM product_warehouse
WHERE rank_product = 1;

--Best and worst selling product line across all warehouse (question 5)
SELECT
	product_line,
	SUM(quantity) AS total_quantity,
	(SUM(total) - SUM(payment_fee)) AS net_revenue
FROM sales
GROUP BY product_line
ORDER BY net_revenue DESC;

-- (question 6)
WITH quantities_warehouse AS (
	SELECT
		warehouse,
		product_line,
		ROUND(AVG(unit_price), 2) AS average_price,
		SUM(quantity) AS total_quantity_ordered,
		RANK () OVER(
			PARTITION BY warehouse 
			ORDER BY SUM(quantity) DESC
		) AS highest_ranking,
		RANK () OVER(
			PARTITION BY warehouse
			ORDER BY SUM(quantity) 
		) AS lowest_ranking
FROM sales
GROUP BY warehouse, product_line

)

SELECT 
	warehouse, 
	product_line,  
	average_price, 
	total_quantity_ordered,
	highest_ranking
FROM quantities_warehouse
WHERE highest_ranking = 1 OR lowest_ranking = 1
ORDER BY warehouse, total_quantity_ordered DESC;

-- question 7
SELECT
	product_line,
	SUM(quantity) AS total_ordered
FROM sales
GROUP BY product_line
ORDER BY total_ordered DESC
LIMIT 1;

-- question 8
SELECT
	warehouse,
	client_type,
	COUNT(client_type) AS number_of_orders
FROM sales
GROUP BY client_type, warehouse
ORDER BY warehouse;

-- question 9
SELECT
	client_type,
	payment,
	payment_fee,
	COUNT(payment) AS number_of_orders
FROM sales
GROUP BY client_type, payment, payment_fee
ORDER BY client_type;

-- question 10
WITH monthly_revenue AS (
	SELECT
		warehouse,
		product_line,
		EXTRACT(MONTH FROM date) AS month_number,
		TO_CHAR(date, 'Month') AS month,
		SUM(total) - SUM(payment_fee) AS net_revenue
	FROM sales
	GROUP BY
		warehouse,
		product_line,
		EXTRACT(MONTH FROM date),
		TO_CHAR(date, 'Month')
) 

SELECT 
	warehouse,
	product_line,
	month,
	net_revenue,
	LAG(net_revenue) OVER(PARTITION BY warehouse, product_line ORDER BY month_number) AS prev_revenue,
	(net_revenue - LAG(net_revenue) OVER(PARTITION BY warehouse, product_line ORDER BY month_number)) AS change_trend
FROM monthly_revenue
ORDER BY warehouse, product_line, month_number;
